### ISSUE TITLE
Update Model Catalogue docs

### ISSUE THREAD

**Issue by izagorac** [JuliaTrustworthyAI/CounterfactualExplanations.jl#369]
When trying to import a PyTorch model as explained in the docs (https://juliatrustworthyai.github.io/CounterfactualExplanations.jl/dev/tutorials/model_catalogue/#Importing-PyTorch-models). I get the following error:
`ERROR: MethodError: no method matching pytorch_model_loader(::String, ::String, ::String, ::String)`

According to Patrick, the code for importing has been moved to `TaijaInteroperability.jl`. This has to be updated in the docs.

**Comment by pat-alt** [comment]
Thanks @izagorac! In the meantime, you should be able to use the method as expected by first importing the package:

```julia
using CounterfactualExplanations
using TaijaInteroperability
...
```

I'm a bit surprised thought that the error message didn't already hint at this, since we've [deprecated](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/blob/main/src/deprecated.jl) the method. 

If it's not too much trouble, can you post a minimum working example here including information about the exact package version you're using?

Thanks!

@kmariuszk for info

**Comment by izagorac** [comment]
Find my code and error message below. Im using CounterfactualExplanations v.0.1.31.

```julia
model_loaded = CounterfactualExplanations.Models.pytorch_model_loader(
        "$(pwd())/docs/src/tutorials/miscellaneous",
        "neural_network_class",
        "NeuralNetwork",
        "$(pwd())/docs/src/tutorials/miscellaneous/pretrained_model.pt"
    )

M = CounterfactualExplanations.Models.PyTorchModel(model_loaded, counterfactual_data.likelihood)
```

<img width="727" alt="Screenshot 2023-12-11 at 11 35 36" src="https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/assets/33690862/23c53342-30be-48ef-bcc8-51c799c3bb1f">

**Comment by pat-alt** [comment]
Can you try instead:

```julia
model_loaded = TaijaInteroperability.pytorch_model_loader(...)
```

**Comment by izagorac** [comment]
It gives the exact same error. I'm using TaijaInteroperability v.0.1.0

**Comment by pat-alt** [comment]
Hmm alright thanks! @kmariuszk any idea what's going on here?

**Comment by kmariuszk** [comment]
Hey @izagorac, did you also activate the `PythonCall` package in your environment?

To give you a better overview of what I mean: Python and R functionality are [package extensions](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)) in `TaijaInteroperability.jl`, which means you have to activate some weak dependencies to make them activate their appropriate functionality, so if you want to use Python functionality you have to run `using TaijaInteroperability, PythonCall` and the same applies to `RCall`. We did this to minimize the pain of users waiting for both `PythonCall` and `RCall` pre-compilation and to minimize the chance of errors caused by using both of these packages in the same environment.

Let me know if it solves the problem!

**Comment by kmariuszk** [comment]
Also, @pat-alt regarding this bit:

> I'm a bit surprised thought that the error message didn't already hint at this, since we've [deprecated](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/blob/main/src/deprecated.jl) the method.

We didn't release the latest version of package and thus users can still use PyTorch functionality in the original way, i.e., `using CounterfactualExplanations, PythonCall`

**Comment by pat-alt** [comment]
> Also, @pat-alt regarding this bit:
> 
> > I'm a bit surprised thought that the error message didn't already hint at this, since we've [deprecated](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/blob/main/src/deprecated.jl) the method.
> 
> We didn't release the latest version of package and thus users can still use PyTorch functionality in the original way, i.e., `using CounterfactualExplanations, PythonCall`

Ah yes, of course! Thanks for checking @kmariuszk

**Comment by izagorac** [comment]
Thanks @kmariuszk and @pat-alt, it works when `using PythonCall`. Before I was `using PyCall`, does that mean that that package is not necessary anymore?

**Comment by kmariuszk** [comment]
> Thanks @kmariuszk and @pat-alt, it works when `using PythonCall`. Before I was `using PyCall`, does that mean that that package is not necessary anymore?

Yes, we decided not to use `PyCall` quite some time ago due to some bugs it was introducing. We're going to work on updating the documentation in the upcoming two weeks, so (hopefully) you won't experience such ambiguities anymore
